from __future__ import annotations

import json
from pathlib import Path

from sentence_transformers import SentenceTransformer


# ============================================================
# PATHS
# ============================================================

PROJECT_ROOT = Path(__file__).resolve().parents[2]

CHUNKS_FILE = PROJECT_ROOT / "rag" / "chunks" / "chunks.json"

EMBEDDINGS_DIR = PROJECT_ROOT / "rag" / "embeddings"

EMBEDDINGS_FILE = EMBEDDINGS_DIR / "embeddings.json"


# ============================================================
# EMBEDDING MODEL
# ============================================================

MODEL_NAME = "sentence-transformers/all-MiniLM-L6-v2"


# ============================================================
# LOAD CHUNKS
# ============================================================

def load_chunks() -> list[dict]:
    """
    Load chunk records generated by document_chunker.py.
    """

    if not CHUNKS_FILE.exists():
        raise FileNotFoundError(
            f"Chunks file not found: {CHUNKS_FILE}"
        )

    with CHUNKS_FILE.open(
        "r",
        encoding="utf-8",
    ) as file:

        chunks = json.load(file)

    if not isinstance(chunks, list):
        raise ValueError(
            "chunks.json must contain a JSON list."
        )

    return chunks


# ============================================================
# CREATE EMBEDDINGS
# ============================================================

def create_embeddings(
    chunks: list[dict],
) -> list[dict]:
    """
    Generate one vector embedding for every chunk.
    """

    if not chunks:
        return []

    texts = []

    for index, chunk in enumerate(chunks):

        if not isinstance(chunk, dict):
            raise ValueError(
                f"Invalid chunk at index {index}."
            )

        text = chunk.get("text")

        if not isinstance(text, str) or not text.strip():
            raise ValueError(
                f"Chunk {index} has no valid text."
            )

        texts.append(text)

    print()
    print("=" * 70)
    print("RAG EMBEDDING GENERATION")
    print("=" * 70)
    print()
    print(f"Embedding model: {MODEL_NAME}")
    print(f"Chunks to embed: {len(texts)}")
    print()

    model = SentenceTransformer(
        MODEL_NAME
    )

    vectors = model.encode(
        texts,
        show_progress_bar=True,
        normalize_embeddings=True,
    )

    records = []

    for index, (chunk, vector) in enumerate(
        zip(chunks, vectors)
    ):

        records.append(
            {
                "text": chunk["text"],
                "metadata": chunk.get(
                    "metadata",
                    {},
                ),
                "embedding": vector.tolist(),
            }
        )

    return records


# ============================================================
# SAVE EMBEDDINGS
# ============================================================

def save_embeddings(
    records: list[dict],
) -> None:
    """
    Save chunk text, metadata, and embeddings.
    """

    EMBEDDINGS_DIR.mkdir(
        parents=True,
        exist_ok=True,
    )

    with EMBEDDINGS_FILE.open(
        "w",
        encoding="utf-8",
    ) as file:

        json.dump(
            records,
            file,
            ensure_ascii=False,
        )

    print()
    print(
        f"Saved {len(records)} embeddings to:"
    )
    print(EMBEDDINGS_FILE)


# ============================================================
# MAIN
# ============================================================

def main() -> None:

    chunks = load_chunks()

    print(
        f"Loaded {len(chunks)} chunks."
    )

    records = create_embeddings(
        chunks
    )

    if not records:
        print("No embeddings generated.")
        return

    save_embeddings(records)

    embedding_dimension = len(
        records[0]["embedding"]
    )

    print()
    print(
        f"Embedding dimension: "
        f"{embedding_dimension}"
    )

    print()
    print(
        "Embedding generation completed successfully."
    )


if __name__ == "__main__":
    main()